version: '3'

services:

  redis:
    container_name: messenger-redis
    build: ./redis
    ports:
      - '6377:6379'
    volumes:
      - ./redis/redis-data:/data
    environment:
      - REDIS_PASSWORD=default-password
    healthcheck:
      test: exit 0

  db:
    container_name: messenger-db
    build: ./db
    ports:
      - '5438:5432'
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  storage:
    container_name: messenger-storage
    build: ./storage
    ports:
      - '4004:3000'
    volumes:
      - './storage:/usr/src/app'
      - './storage/package.json:/usr/src/package.json'

  server:
    container_name: messenger-server
    build: ./server
    ports:
      - '4001:3000'
    volumes:
      - './server:/usr/src/app'
      - './server/package.json:/usr/src/package.json'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@messenger-db:5432/messenger_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@messenger-db:5432/messenger_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
      - REDIS_PASSWORD=default-password
      - GMAIL_USER=
      - GMAIL_PASSWORD=
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  web-client:
    container_name: messenger-web-client
    build: ./client
    ports:
      - '4000:3000'
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
