version: '3'

services:

  db:
    container_name: messenger-db
    build: ./db
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  server:
    container_name: messenger-server
    build: ./server
    volumes:
      - './server:/usr/src/app'
      - './server/package.json:/usr/src/package.json'
    ports:
      - '4000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@messenger-db:5432/messenger_dev
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
    depends_on:
      - db
    links:
      - db

  web-client:
    container_name: messenger-web-client
    build: ./client
    volumes:
      - './client:/usr/src/app'
      - './client/package.json:/usr/src/package.json'
    ports:
      - '4001:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - CHOKIDAR_USEPOLLING=true
