version: "3.3"

services:
  redis:
    container_name: redis
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-data:/data
    environment:
      - REDIS_PASSWORD=redis
    healthcheck:
      test: exit 0

  channel-db:
    container_name: channel-db
    build: ./channel-db
    ports:
      - "5432:5432"
    volumes:
      - ./channel-db/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
    healthcheck:
      test: exit 0

  message-db:
    container_name: message-db
    build: ./message-db
    ports:
      - "27017:27017"
    volumes:
      - ./message-db/mongo-data:/data/db
    environment:
      - MONGODB_USER=mongo
      - MONGODB_PASSWORD=mongo
    healthcheck:
      test: exit 0

  channel-service:
    container_name: channel-service
    build: ./channel-service
    ports:
      - "4000:3000"
    volumes:
      - "./channel-service:/usr/src/app"
      - "./channel-service/package.json:/usr/src/package.json"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=postgres://postgres:postgres@channel-db:5432/workspace_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@channel-db:5432/workspace_test
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
      - REDIS_PASSWORD=redis
    depends_on:
      - channel-db
      - redis
    links:
      - channel-db
      - redis

  message-service:
    container_name: message-service
    build: ./message-service
    ports:
      - "4001:3000"
    volumes:
      - "./message-service:/usr/src/app"
      - "./message-service/package.json:/usr/src/package.json"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=mongo://partners-db:27017/message_dev
      - DATABASE_TEST_URL=mongo://partners-db:27017/message_test
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
      - REDIS_PASSWORD=redis
    depends_on:
      - message-db
      - redis
    links:
      - message-db
      - redis

  call-service:
    container_name: call-service
    build: ./call-service
    ports:
      - "4002:3000"
    volumes:
      - "./call-service:/usr/src/app"
      - "./call-service/package.json:/usr/src/package.json"
    environment:
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
      - REDIS_PASSWORD=redis
    depends_on:
      - redis
    links:
      - redis

  file-service:
    container_name: file-service
    build: ./file-service
    ports:
      - "4003:5000"
    volumes:
      - "./file-service:/usr/src/app"
      - "./file-service/requirements.txt:/usr/src/requirements.txt"
    environment:
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe
      - TOKEN_SECRET_2=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe

  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - "./nginx:/etc/nginx/conf.d"
  #     - "./file-service/app/static:/files"
  #   depends_on:
  #     - channel-service
  #     - message-service
  #     - call-service
  #     - assistant-service
  #     - file-service
  #   restart: always
  #   healthcheck:
  #     test: exit 0
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx \
  #     -s reload; done & nginx -g \"daemon off;\"'"